### ISSUE TITLE
"catberry init example" does nothing, with no output

### ISSUE THREAD

**Issue by Maia-Everett** [catberry/catberry-cli#1]
I'm trying catberry-cli under Ubuntu 14.04.

I did:

```
$ sudo apt-get install node npm
$ sudo npm -g install catberry-cli
npm WARN engine catberry-cli@2.0.0: wanted: {"node":"~0.10.26"} (current: {"node":"v0.10.25","npm":"1.3.10"})

npm http GET https://registry.npmjs.org/ncp
<snip>
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
/usr/local/bin/catberry -> /usr/local/lib/node_modules/catberry-cli/bin/catberry.js
catberry-cli@2.0.0 /usr/local/lib/node_modules/catberry-cli
├── commander@2.3.0
├── ncp@0.6.0
├── split@0.3.0 (through@2.3.6)
└── mkdirp@0.5.0 (minimist@0.0.8)
```

Yet when I invoke `catberry` with any arguments (including `catberry init example`), it does nothing and prints nothing.

**Comment by asdf404** [comment]
Have same issue. `catberry init example` does nothing with 100% cpu usage. I've been awaiting for 10 minutes and it only created empty files.
I'm using IO.JS 1.5.0. It has been installed without any problems or warnings with `npm install catberry-cli -g`.

**Comment by pragmadash** [comment]
@asdf404 Are you sure you have the same issue? 
The problem described in this issue is about wrong `node` package in Ubuntu/Debian repository. I think you have a different one.

Anyway, what is the output `node --version`?

**Comment by asdf404** [comment]
@pragmadash 
```sh
vagrant@box:~$ node --version
v1.5.0
```

I've installed it from official io.js repo https://iojs.org/dist/

**Comment by pragmadash** [comment]
Ok, I need more details about your environment. 
What is your OS? What empty files appear in your directory? I will reproduce your environment using VirtualBox and let you know.

**Comment by asdf404** [comment]
I'm using Ubuntu 14.04 in VirtualBox. Empty files is structure of [this](https://github.com/catberry/catberry-cli/tree/master/templates/example) example with no content.

**Comment by pragmadash** [comment]
@asdf404 it was a problem with [ncp package](https://www.npmjs.com/package/ncp) which is used for copying files recursively. I have updated it in [this release](https://github.com/catberry/catberry-cli/releases/tag/4.0.3). It was published to NPM already.

**Comment by asdf404** [comment]
@pragmadash awesome! Thanks.
