### ISSUE TITLE
Troubles with the debug-win npm script

### ISSUE THREAD

**Issue by ForNeVeR** [catberry/catberry-cli#5]
The generated projects includes npm script called `debug-win`. It creates two node processes and offers no way of killing both of them.

**Comment by pragmadash** [comment]
Okay, I'll think how to solve this problem.

**Comment by ForNeVeR** [comment]
I am thinking about it already, wait for PR :)

**Comment by pragmadash** [comment]
@ForNeVeR awesome! It's up to you!
